### ISSUE TITLE
Scrypted Web UI won't open / "site can't be reached"

### ISSUE THREAD

**Issue by odubman** [aegjoyce/ha-addons#26]
I have the Scrypted full version installed as add-on into HA via HACs.  When trying to open Web UI, I get the Scrypted login screen, but after entering UN/PW, get error that site can't be reached and "homeassistant.local refused to connect".  I've allowed this site as insecure, but I never get any other certificate pop-ups to allow.  Below is log:

i Scrypted Core loading @scrypted/core
i Scrypted Core pid 38
#######################################################
Scrypted Volume           : /data/scrypted_data
Scrypted Server (Local)   : https://localhost:10443/
Scrypted Server (Remote)  : https://172.17.232.1:10443/
Scrypted Server (Remote)  : https://192.168.86.32:10443/
Scrypted Server (Remote)  : https://172.30.32.1:10443/
Scrypted Server (Remote)  : https://fe80::42:10ff:fee8:cdd:10443/
Scrypted Server (Remote)  : https://fd47:df7f:e727:0:8a17:ac6d:b67e:444f:10443/
Scrypted Server (Remote)  : https://fe80::1a90:18d9:22b6:26bb:10443/
Scrypted Server (Remote)  : https://fe80::42:78ff:fe7f:9d75:10443/
Scrypted Server (Remote)  : https://fe80::75:6bff:feca:cdc7:10443/
Scrypted Server (Remote)  : https://fe80::4028:beff:fef2:89d4:10443/
Scrypted Server (Remote)  : https://fe80::c037:93ff:fefa:737d:10443/
Scrypted Server (Remote)  : https://fe80::885f:2cff:feab:d871:10443/
Scrypted Server (Remote)  : https://fe80::6019:caff:feb7:cc85:10443/
Scrypted Server (Remote)  : https://fe80::ec0e:84ff:fe04:5043:10443/
Scrypted Server (Remote)  : https://fe80::786d:e6ff:fe6b:e7bf:10443/
Version:       : 0.6.4
#######################################################
Scrypted insecure http service port: 11080
Ports can be changed with environment variables.
https: $SCRYPTED_SECURE_PORT
http : $SCRYPTED_INSECURE_PORT
Certificate can be modified via tls.createSecureContext options in
JSON file located at SCRYPTED_HTTPS_OPTIONS_FILE environment variable:
export SCRYPTED_HTTPS_OPTIONS_FILE=/path/to/options.json
https://nodejs.org/api/tls.html#tlscreatesecurecontextoptions
#######################################################

**Comment by boojew** [comment]
I have the same issue.  Opening the login page crashes the addon. Not sure why :( I see a lot of errors, but they dont look related.

` at PluginDeviceProxyHandler.probe (/server/node_modules/@scrypted/server/src/plugin/plugin-device.ts:358:13)
unhandledRejection host:@scrypted/prebuffer-mixin
@scrypted/prebuffer-mixin:host
thread:main
host:@scrypted/prebuffer-mixin
host:@scrypted/prebuffer-mixin
@scrypted/webrtc:host
host:@scrypted/webrtc
Error: device is unavailable 24 (mixin undefined)
    at PluginDeviceProxyHandler.applyMixin (/server/node_modules/@scrypted/server/src/plugin/plugin-device.ts:372:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:574:37) {
  cause: undefined
}
e Rebroadcast Plugin unhandledRejection Error: @scrypted/prebuffer-mixin:host: host:@scrypted/prebuffer-mixin: main:thread: @scrypted/prebuffer-mixin:host: @scrypted/prebuffer-mixin:host: host:@scrypted/webrtc: @scrypted/webrtc:host: device is unavailable 24 (mixin undefined)
[Front Door] prebuffer sessions starting in 5 seconds
e Rebroadcast Plugin unhandledRejection Error: @scrypted/prebuffer-mixin:host: host:@scrypted/prebuffer-mixin: main:thread: @scrypted/prebuffer-mixin:host: @scrypted/prebuffer-mixin:host: host:@scrypted/webrtc: @scrypted/webrtc:host: device is unavailable 23 (mixin undefined)
unhandledRejection host:@scrypted/prebuffer-mixin
@scrypted/prebuffer-mixin:host
thread:main
host:@scrypted/prebuffer-mixin
host:@scrypted/prebuffer-mixin
@scrypted/webrtc:host
host:@scrypted/webrtc
Error: device is unavailable 23 (mixin undefined)
    at PluginDeviceProxyHandler.applyMixin (/server/node_modules/@scrypted/server/src/plugin/plugin-device.ts:372:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:574:37) {
  cause: undefined
}
terminating worker for mixin release
terminating worker for mixin release
prebuffer worker error non-zero result: 1
unhandledRejection RPCResultError: main:thread: RpcPeer has been killed
    at RpcProxy.apply (/server/node_modules/@scrypted/server/src/rpc.ts:135:35)
    at /server/node_modules/@scrypted/server/src/plugin/plugin-remote.ts:422:28
    at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:577:43)
    at RpcPeer.handleMessage (/server/node_modules/@scrypted/server/src/rpc.ts:527:18)
    at process.<anonymous> (/server/node_modules/@scrypted/server/src/scrypted-plugin-main.ts:30:43)
    at process.emit (node:events:513:28)
    at process.emit (node:domain:489:12)
    at process.emit (/server/node_modules/source-map-support/source-map-support.js:516:21)
    at emit (node:internal/child_process:937:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  cause: undefined
}
unhandledRejection RPCResultError: main:thread: RpcPeer has been killed
    at RpcProxy.apply (/server/node_modules/@scrypted/server/src/rpc.ts:135:35)
    at /server/node_modules/@scrypted/server/src/plugin/plugin-remote.ts:422:28
    at RpcPeer.handleMessageInternal (/server/node_modules/@scrypted/server/src/rpc.ts:577:43)
    at RpcPeer.handleMessage (/server/node_modules/@scrypted/server/src/rpc.ts:527:18)
    at process.<anonymous> (/server/node_modules/@scrypted/server/src/scrypted-plugin-main.ts:30:43)
    at process.emit (node:events:513:28)
    at process.emit (node:domain:489:12)
    at process.emit (/server/node_modules/source-map-support/source-map-support.js:516:21)
    at emit (node:internal/child_process:937:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  cause: undefined
}
e Rebroadcast Plugin unhandledRejection Error: main:thread: RpcPeer has been killed
e Rebroadcast Plugin unhandledRejection Error: main:thread: RpcPeer has been killed
prebuffer worker error non-zero result: 1
Register request has failed with Error=PHONE_REGISTRATION_ERROR
Retry... 1
[Backyard] prebuffer sessions starting in 5 seconds
[Front Door] prebuffer sessions starting in 5 seconds
[Backyard] stream SIP will be rebroadcast on demand.
[Backyard] stream WebRTC will be rebroadcast on demand.
[Front Door] stream SIP will be rebroadcast on demand.
[Front Door] stream WebRTC will be rebroadcast on demand.
[Front Door] HomeKit Connection ::ffff:192.168.0.62
Register request has failed with Error=PHONE_REGISTRATION_ERROR
Retry... 2
[Backyard] HomeKit Connection ::ffff:192.168.0.62
HomeKit Connection ::ffff:192.168.0.62
(node:56) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)`

**Comment by boojew** [comment]
Latest update seems to have fixed the issue for me

**Comment by aegjoyce** [comment]
Issues also seen on the last few docker images - please update to latest version and report back if still causing issues
